spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:marketlens}

  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:marketlens}

logging:
  level:
    root: WARN
    io.kaeum.marketlens: INFO
